# Generated by Django 3.1.7 on 2021-03-10 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=90)),
                ('target', models.CharField(max_length=24)),
                ('start', models.DateTimeField(default=datetime.datetime(2021, 3, 10, 22, 21, 28, 473082))),
                ('end', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
